### ISSUE TITLE
Fails on Python 3.10

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/hypercube#24]
Busy porting the ecosystem to Python 3.10. Seeing issues downstream

@sjperkins can you please give me maintenance access on pypi for this?
```
======================================================================                                                                            
ERROR: Failure: ImportError (cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py))                       
----------------------------------------------------------------------                                                                            
Traceback (most recent call last):                                                                                                                
  File "/usr/local/lib/python3.10/dist-packages/nose/failure.py", line 35, in runTest                                                             
    raise self.exc_val.with_traceback(self.tb)                                                                                                    
  File "/usr/local/lib/python3.10/dist-packages/nose/loader.py", line 337, in loadTestsFromName                                                   
    module = self.importer.importFromPath(                                                                                                        
  File "/usr/local/lib/python3.10/dist-packages/nose/importer.py", line 157, in importFromPath                                                    
    return self.importFromDir(dir_path, fqname)                                                                                                   
  File "/usr/local/lib/python3.10/dist-packages/nose/importer.py", line 193, in importFromDir                                                     
    mod = load_module(part_fqname, fh, filename, desc)                                                                                            
  File "/usr/local/lib/python3.10/dist-packages/nose/importer.py", line 124, in load_module                                                       
    spec.loader.exec_module(mod)                                                                                                                  
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module                                                                         
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed                                                                    
  File "/src/montblanc/montblanc/tests/beam_factory.py", line 7, in <module>                                                                      
    from montblanc.impl.rime.tensorflow.sources.fits_beam_source_provider import (                                                                
  File "/src/montblanc/montblanc/impl/rime/tensorflow/sources/__init__.py", line 21, in <module>                                                  
    from .source_context import SourceContext                                                                                                     
  File "/src/montblanc/montblanc/impl/rime/tensorflow/sources/source_context.py", line 22, in <module>                                            
    from ..hypercube_proxy_metaclass import HypercubeProxyMetaClass                                                                               
  File "/src/montblanc/montblanc/impl/rime/tensorflow/hypercube_proxy_metaclass.py", line 27, in <module>                                         
    from hypercube import HyperCube                                                                                                               
  File "/usr/local/lib/python3.10/dist-packages/hypercube/__init__.py", line 21, in <module>                                                      
    from hypercube.base_cube import HyperCube                                                                                                     
  File "/usr/local/lib/python3.10/dist-packages/hypercube/base_cube.py", line 28, in <module>                                                     
    from attrdict import AttrDict                                                                                                                 
  File "/usr/local/lib/python3.10/dist-packages/attrdict/__init__.py", line 5, in <module>                                                        
    from attrdict.mapping import AttrMap                                                                                                          
  File "/usr/local/lib/python3.10/dist-packages/attrdict/mapping.py", line 4, in <module>                                                         
    from collections import Mapping                                                                                                               
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)     
```

**Comment by bennahugo** [comment]
Thanks! I will iteratively work through all the failures and push releases for Python 3.10
