### ISSUE TITLE
MemoryError while running gridding example

### ISSUE THREAD

**Issue by jfunction** [ska-sa/hypercube#9]
Hey - so I'm getting a MemoryError when I run gridding.py (from console or in my debugger). The (debugger) output is:
```
Registered Dimensions
--------------------------------------------------------------------------------
Dimension Name Description         Global Size Local Size  Extents        
--------------------------------------------------------------------------------
facet_height   Facet Height        128         128         (0, 128)       
facet_width    Facet Width         128         128         (0, 128)       
grid_height    Grid Height         10240       10240       (0, 10240)     
grid_width     Grid Width          10240       10240       (0, 10240)     
nchan          Channels            32768       32768       (0, 32768)     
nfacet         Facets              64          64          (0, 64)        
npol           Polarisations       4           4           (0, 4)         

Registered Arrays
--------------------------------------------------------------------------------
Array Name          Size      Type           Shape                              
--------------------------------------------------------------------------------
facets              2.0TB     complex128     (nfacet,facet_width,facet_height,nchan,npol)
main_grid           200.0TB   complex128     (grid_width,grid_height,nchan,npol)
--------------------------------------------------------------------------------
Local Memory Usage: 202.0TB
--------------------------------------------------------------------------------






REDUCING LOCAL PROBLEM SIZE
 grid_width => 256
 grid_height => 256
 nchan => 128
 
Note: extents[1] - extents[0] <= local_size




Registered Dimensions
--------------------------------------------------------------------------------
Dimension Name Description         Global Size Local Size  Extents        
--------------------------------------------------------------------------------
facet_height   Facet Height        128         128         (0, 128)       
facet_width    Facet Width         128         128         (0, 128)       
grid_height    Grid Height         10240       256         (1000, 1256)   
grid_width     Grid Width          10240       256         (1000, 1256)   
nchan          Channels            32768       128         (600, 700)     
nfacet         Facets              64          64          (0, 64)        
npol           Polarisations       4           4           (0, 4)         

Registered Arrays
--------------------------------------------------------------------------------
Array Name          Size      Type           Shape                              
--------------------------------------------------------------------------------
facets              8.0GB     complex128     (nfacet,facet_width,facet_height,nchan,npol)
main_grid           512.0MB   complex128     (grid_width,grid_height,nchan,npol)
--------------------------------------------------------------------------------
Local Memory Usage: 8.5GB
--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/jared/pycharm-5.0/helpers/pydev/pydevd.py", line 2403, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jared/pycharm-5.0/helpers/pydev/pydevd.py", line 1794, in run
    launch(file, globals, locals)  # execute the script
  File "/home/jared/git/hypercube/hypercube/examples/gridding.py", line 82, in <module>
    hc.create_local_numpy_arrays_on_cube(np_cube)
  File "build/bdist.linux-x86_64/egg/hypercube/array_factory.py", line 133, in create_local_arrays_on_cube
  File "build/bdist.linux-x86_64/egg/hypercube/array_factory.py", line 89, in create_local_arrays
  File "build/bdist.linux-x86_64/egg/hypercube/array_factory.py", line 89, in <dictcomp>
MemoryError
```
I'll take a look a bit later today, but I wondered if the issue was anything obvious? 
Other notes:
  Machine: Intel i7@2.5GHz 64-bit, 8GB RAM
  OS: Ubuntu 14.04 inside VirtualBox 4.3.20 VM w/Guest Additions
  Installed with: `python setup.py --user`

**Comment by jfunction** [comment]
Looking further into it I see that the error is being raised by numpys empty method. We have asked numpy to create an empty `dtype=np.complex128` valued array of `shape=(64, 128, 128, 128, 4)` and it felt like we asked a bit much so it complained. 

I'm not sure of the intention here, but I'm guessing the shape data should be carved into more digestible chunks? Maybe there should be a warning to that effect, since "MemoryError" may be a little vague (though in retrospect I see that it is in fact a memory error).

Does this sound right and if so should I add something like this and submit a PR?:
```python
try:
    hc.create_local_numpy_arrays_on_cube(np_cube)
except MemoryError as e:
    print("There was an error carving up the cube - the shape is too large.")
```

**Comment by sjperkins** [comment]
Hi @jfunction, sorry I've realised I wasn't watching the repository so I've only seen this issue now. 

hypercube doesn't automatically subdivide the problem since this is problem specific. So you have to do this yourself, by specifying the local_size of your array and then seeing if it fits within some memory budget.

I've implemented a function [viable_dim_config](https://github.com/ska-sa/montblanc/blob/cb6de08115ab759c16a8d71c837f51085a43fb09/montblanc/util/__init__.py#L169) called [here](https://github.com/ska-sa/montblanc/blob/cb6de08115ab759c16a8d71c837f51085a43fb09/montblanc/impl/rime/v5/CompositeRimeSolver.py#L633-L647) that does this sort of thing relatively automatically for montblanc.

I'm considering moving viable_dim_config into hypercube.

**Comment by sjperkins** [comment]
Closed, opened an enhancement for the budgeting behaviour in #21 .
